//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImplementUnifiedFramework
{
    using  System;
    using  System.Collections.Generic;
    using  System.Linq;
    using  System.Text;
    using  System.Threading.Tasks;
    using  OpenQA.Selenium;
    using  OpenQA.Selenium.IE;
    using  OpenQA.Selenium.Support.UI;
    using  Microsoft.VisualStudio.TestTools.UnitTesting;
    using  System.Diagnostics;
    using  System.IO;
    using  System.Configuration;
    using  System.Threading;
    using  UnifiedFramework.UnifiedReports;
    using  UnifiedFrameWork.Controller;
    using  System.Text.RegularExpressions;
    using  Winium.Desktop.Driver;
    using  OpenQA.Selenium.Remote;
    using  UnifiedFrameWork.UnifiedComponents;
    
    
    [TestClass()]
    public class BVT_TestMethod : Config
    {
        
        [TestMethod()]
        [TestCategory("BVT ")]
        [Description("Test title to validate Scenario from BVT Test Suite:Scenario 1")]
        public void Verify_Test_Case_1001()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from BVT Test Suite:Scenario 1"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("Regression")]
        [Description("Test title to validate Scenario from Regression Test Suite:Scenario 1")]
        public void Verify_Test_Case_1002()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from Regression Test Suite:Scenario 1"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("Regression")]
        [Description("Test title to validate Scenario from Regression Test Suite:Scenario 2")]
        public void Verify_Test_Case_1003()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from Regression Test Suite:Scenario 2"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("Regression")]
        [Description("Test title to validate Scenario from Regression Test Suite:Scenario 3")]
        public void Verify_Test_Case_1004()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from Regression Test Suite:Scenario 3"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("BVT ")]
        [Description("Test title to validate Scenario from BVT Test Suite:Scenario 2")]
        public void Verify_Test_Case_1005()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from BVT Test Suite:Scenario 2"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("BVT ")]
        [Description("Test title to validate Scenario from BVT Test Suite:Scenario 3")]
        public void Verify_Test_Case_1006()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from BVT Test Suite:Scenario 3"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("Regression")]
        [Description("Test title to validate Scenario from Regression Test Suite:Scenario 4")]
        public void Verify_Test_Case_1007()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from Regression Test Suite:Scenario 4"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("BVT ")]
        [Description("Test title to validate Scenario from BVT Test Suite:Scenario 4")]
        public void Verify_Test_Case_1008()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from BVT Test Suite:Scenario 4"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("BVT ")]
        [Description("Test title to validate Scenario from BVT Test Suite:Scenario 5")]
        public void Verify_Test_Case_1009()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from BVT Test Suite:Scenario 5"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
        
        [TestMethod()]
        [TestCategory("Regression")]
        [Description("Test title to validate Scenario from Regression Test Suite:Scenario 5")]
        public void Verify_Test_Case_1010()
        {
            unifiedLogCollection.Add(unifiedReport.StartTest("Test title to validate Scenario from Regression Test Suite:Scenario 5"));;
            try
            {
                // Please fill in you code here
            }
            catch (System.Exception ex)
            {
                // Code to handle the Exception
            }
            finally
            {
                // Handle any finally block
            }
        }
    }
}
